# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'item.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(521, 111)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(0, 0, 521, 111))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.widget = QtWidgets.QWidget(self.frame)
        self.widget.setGeometry(QtCore.QRect(40, 10, 461, 91))
        self.widget.setObjectName("widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_6.addWidget(self.label)
        self.qt_value_time = QtWidgets.QLabel(self.widget)
        self.qt_value_time.setMinimumSize(QtCore.QSize(180, 0))
        self.qt_value_time.setObjectName("qt_value_time")
        self.horizontalLayout_6.addWidget(self.qt_value_time)
        self.label_11 = QtWidgets.QLabel(self.widget)
        self.label_11.setMaximumSize(QtCore.QSize(50, 16777215))
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_6.addWidget(self.label_11)
        self.qt_value_count = QtWidgets.QLabel(self.widget)
        self.qt_value_count.setObjectName("qt_value_count")
        self.horizontalLayout_6.addWidget(self.qt_value_count)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.qt_naming_lu = QtWidgets.QLabel(self.widget)
        self.qt_naming_lu.setMaximumSize(QtCore.QSize(80, 16777215))
        self.qt_naming_lu.setAlignment(QtCore.Qt.AlignCenter)
        self.qt_naming_lu.setObjectName("qt_naming_lu")
        self.horizontalLayout.addWidget(self.qt_naming_lu)
        self.qt_value_lu = QtWidgets.QLabel(self.widget)
        self.qt_value_lu.setObjectName("qt_value_lu")
        self.horizontalLayout.addWidget(self.qt_value_lu)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.qt_naming_ld = QtWidgets.QLabel(self.widget)
        self.qt_naming_ld.setMaximumSize(QtCore.QSize(80, 16777215))
        self.qt_naming_ld.setAlignment(QtCore.Qt.AlignCenter)
        self.qt_naming_ld.setObjectName("qt_naming_ld")
        self.horizontalLayout_2.addWidget(self.qt_naming_ld)
        self.qt_value_ld = QtWidgets.QLabel(self.widget)
        self.qt_value_ld.setObjectName("qt_value_ld")
        self.horizontalLayout_2.addWidget(self.qt_value_ld)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_5.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.qt_naming_ru = QtWidgets.QLabel(self.widget)
        self.qt_naming_ru.setMaximumSize(QtCore.QSize(80, 16777215))
        self.qt_naming_ru.setAlignment(QtCore.Qt.AlignCenter)
        self.qt_naming_ru.setObjectName("qt_naming_ru")
        self.horizontalLayout_3.addWidget(self.qt_naming_ru)
        self.qt_value_ru = QtWidgets.QLabel(self.widget)
        self.qt_value_ru.setObjectName("qt_value_ru")
        self.horizontalLayout_3.addWidget(self.qt_value_ru)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.qt_naming_rd = QtWidgets.QLabel(self.widget)
        self.qt_naming_rd.setMaximumSize(QtCore.QSize(80, 16777215))
        self.qt_naming_rd.setAlignment(QtCore.Qt.AlignCenter)
        self.qt_naming_rd.setObjectName("qt_naming_rd")
        self.horizontalLayout_4.addWidget(self.qt_naming_rd)
        self.qt_value_rd = QtWidgets.QLabel(self.widget)
        self.qt_value_rd.setObjectName("qt_value_rd")
        self.horizontalLayout_4.addWidget(self.qt_value_rd)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Time"))
        self.qt_value_time.setText(_translate("Form", "time"))
        self.label_11.setText(_translate("Form", "Count"))
        self.qt_value_count.setText(_translate("Form", "count"))
        self.qt_naming_lu.setText(_translate("Form", "R1"))
        self.qt_value_lu.setText(_translate("Form", "r1 value"))
        self.qt_naming_ld.setText(_translate("Form", "R2"))
        self.qt_value_ld.setText(_translate("Form", "r2 value"))
        self.qt_naming_ru.setText(_translate("Form", "R3"))
        self.qt_value_ru.setText(_translate("Form", "r3 value"))
        self.qt_naming_rd.setText(_translate("Form", "R4"))
        self.qt_value_rd.setText(_translate("Form", "r4 value"))

