# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1927, 1138)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        MainWindow.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        MainWindow.setFont(font)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        MainWindow.setStyleSheet("*{ background-color:rgb(255, 255, 255); font:  bold 18pt \"나눔고딕\";}\n"
"\n"
"")
        MainWindow.setAnimated(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName("centralwidget")
        self.layer_R4 = QtWidgets.QLCDNumber(self.centralwidget)
        self.layer_R4.setEnabled(True)
        self.layer_R4.setGeometry(QtCore.QRect(770, 660, 100, 30))
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.layer_R4.setFont(font)
        self.layer_R4.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.layer_R4.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.layer_R4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.layer_R4.setLineWidth(5)
        self.layer_R4.setSmallDecimalPoint(False)
        self.layer_R4.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.layer_R4.setObjectName("layer_R4")
        self.layer_R1 = QtWidgets.QLCDNumber(self.centralwidget)
        self.layer_R1.setEnabled(True)
        self.layer_R1.setGeometry(QtCore.QRect(770, 290, 100, 30))
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.layer_R1.setFont(font)
        self.layer_R1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.layer_R1.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.layer_R1.setFrameShadow(QtWidgets.QFrame.Plain)
        self.layer_R1.setLineWidth(5)
        self.layer_R1.setSmallDecimalPoint(False)
        self.layer_R1.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.layer_R1.setObjectName("layer_R1")
        self.layer_R3 = QtWidgets.QLCDNumber(self.centralwidget)
        self.layer_R3.setEnabled(True)
        self.layer_R3.setGeometry(QtCore.QRect(770, 530, 100, 30))
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.layer_R3.setFont(font)
        self.layer_R3.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.layer_R3.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.layer_R3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.layer_R3.setLineWidth(5)
        self.layer_R3.setSmallDecimalPoint(False)
        self.layer_R3.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.layer_R3.setObjectName("layer_R3")
        self.layer_L2 = QtWidgets.QLCDNumber(self.centralwidget)
        self.layer_L2.setGeometry(QtCore.QRect(230, 410, 100, 30))
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.layer_L2.setFont(font)
        self.layer_L2.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.layer_L2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.layer_L2.setLineWidth(5)
        self.layer_L2.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.layer_L2.setObjectName("layer_L2")
        self.layer_L3 = QtWidgets.QLCDNumber(self.centralwidget)
        self.layer_L3.setGeometry(QtCore.QRect(230, 530, 100, 30))
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.layer_L3.setFont(font)
        self.layer_L3.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.layer_L3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.layer_L3.setLineWidth(5)
        self.layer_L3.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.layer_L3.setObjectName("layer_L3")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(340, 280, 420, 420))
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.graphicsView.setFont(font)
        self.graphicsView.setFrameShape(QtWidgets.QFrame.Box)
        self.graphicsView.setFrameShadow(QtWidgets.QFrame.Plain)
        self.graphicsView.setLineWidth(2)
        self.graphicsView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.graphicsView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.graphicsView.setObjectName("graphicsView")
        self.layer_L4 = QtWidgets.QLCDNumber(self.centralwidget)
        self.layer_L4.setGeometry(QtCore.QRect(230, 660, 100, 30))
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.layer_L4.setFont(font)
        self.layer_L4.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.layer_L4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.layer_L4.setLineWidth(5)
        self.layer_L4.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.layer_L4.setObjectName("layer_L4")
        self.layer_R2 = QtWidgets.QLCDNumber(self.centralwidget)
        self.layer_R2.setEnabled(True)
        self.layer_R2.setGeometry(QtCore.QRect(770, 410, 100, 30))
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.layer_R2.setFont(font)
        self.layer_R2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.layer_R2.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.layer_R2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.layer_R2.setLineWidth(5)
        self.layer_R2.setSmallDecimalPoint(False)
        self.layer_R2.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.layer_R2.setObjectName("layer_R2")
        self.layer_L1 = QtWidgets.QLCDNumber(self.centralwidget)
        self.layer_L1.setGeometry(QtCore.QRect(230, 290, 100, 30))
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.layer_L1.setFont(font)
        self.layer_L1.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.layer_L1.setFrameShadow(QtWidgets.QFrame.Plain)
        self.layer_L1.setLineWidth(5)
        self.layer_L1.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.layer_L1.setObjectName("layer_L1")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(54, 217, 0, 0))
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.frame.setFont(font)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        self.frame_4.setGeometry(QtCore.QRect(30, 30, 1041, 221))
        self.frame_4.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_4.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.frame_4.setFont(font)
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.layoutWidget = QtWidgets.QWidget(self.frame_4)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 1021, 201))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 41))
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_6.addWidget(self.label_5)
        self.splitter_5 = QtWidgets.QSplitter(self.layoutWidget)
        self.splitter_5.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_5.setObjectName("splitter_5")
        self.splitter = QtWidgets.QSplitter(self.splitter_5)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.img_LR = QtWidgets.QLabel(self.splitter)
        self.img_LR.setMinimumSize(QtCore.QSize(64, 0))
        self.img_LR.setMaximumSize(QtCore.QSize(98, 16777215))
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.img_LR.setFont(font)
        self.img_LR.setText("")
        self.img_LR.setPixmap(QtGui.QPixmap("../Dusan-4/uiFile/arrow.png"))
        self.img_LR.setAlignment(QtCore.Qt.AlignCenter)
        self.img_LR.setObjectName("img_LR")
        self.information_LR = QtWidgets.QLabel(self.splitter)
        self.information_LR.setMaximumSize(QtCore.QSize(405, 16777215))
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.information_LR.setFont(font)
        self.information_LR.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.information_LR.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.information_LR.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.information_LR.setObjectName("information_LR")
        self.splitter_8 = QtWidgets.QSplitter(self.splitter_5)
        self.splitter_8.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_8.setObjectName("splitter_8")
        self.img_UD = QtWidgets.QLabel(self.splitter_8)
        self.img_UD.setMinimumSize(QtCore.QSize(64, 0))
        self.img_UD.setMaximumSize(QtCore.QSize(98, 16777215))
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.img_UD.setFont(font)
        self.img_UD.setText("")
        self.img_UD.setPixmap(QtGui.QPixmap("../Dusan-4/uiFile/arrow.png"))
        self.img_UD.setAlignment(QtCore.Qt.AlignCenter)
        self.img_UD.setObjectName("img_UD")
        self.information_UD = QtWidgets.QLabel(self.splitter_8)
        self.information_UD.setMaximumSize(QtCore.QSize(405, 16777215))
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.information_UD.setFont(font)
        self.information_UD.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.information_UD.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.information_UD.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.information_UD.setObjectName("information_UD")
        self.verticalLayout_6.addWidget(self.splitter_5)
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(160, 800, 931, 201))
        self.frame_3.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.frame_3.setFont(font)
        self.frame_3.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_3.setObjectName("frame_3")
        self.laser_state_RL = QtWidgets.QLabel(self.frame_3)
        self.laser_state_RL.setGeometry(QtCore.QRect(180, 19, 281, 161))
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.laser_state_RL.setFont(font)
        self.laser_state_RL.setStyleSheet("font: bold 13pt \"나눔고딕\";")
        self.laser_state_RL.setAlignment(QtCore.Qt.AlignCenter)
        self.laser_state_RL.setObjectName("laser_state_RL")
        self.frame_5 = QtWidgets.QFrame(self.frame_3)
        self.frame_5.setGeometry(QtCore.QRect(10, 11, 161, 181))
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.frame_5.setFont(font)
        self.frame_5.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setMidLineWidth(0)
        self.frame_5.setObjectName("frame_5")
        self.frame1 = QtWidgets.QFrame(self.frame_5)
        self.frame1.setGeometry(QtCore.QRect(10, 20, 34, 148))
        self.frame1.setStyleSheet("QFrame {background:rgb(0, 0, 0);}")
        self.frame1.setObjectName("frame1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.img_L1 = QtWidgets.QLabel(self.frame1)
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.img_L1.setFont(font)
        self.img_L1.setText("")
        self.img_L1.setAlignment(QtCore.Qt.AlignCenter)
        self.img_L1.setObjectName("img_L1")
        self.verticalLayout.addWidget(self.img_L1)
        self.img_L2 = QtWidgets.QLabel(self.frame1)
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.img_L2.setFont(font)
        self.img_L2.setText("")
        self.img_L2.setAlignment(QtCore.Qt.AlignCenter)
        self.img_L2.setObjectName("img_L2")
        self.verticalLayout.addWidget(self.img_L2)
        self.img_L3 = QtWidgets.QLabel(self.frame1)
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.img_L3.setFont(font)
        self.img_L3.setText("")
        self.img_L3.setAlignment(QtCore.Qt.AlignCenter)
        self.img_L3.setObjectName("img_L3")
        self.verticalLayout.addWidget(self.img_L3)
        self.img_L4 = QtWidgets.QLabel(self.frame1)
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.img_L4.setFont(font)
        self.img_L4.setText("")
        self.img_L4.setAlignment(QtCore.Qt.AlignCenter)
        self.img_L4.setObjectName("img_L4")
        self.verticalLayout.addWidget(self.img_L4)
        self.frame2 = QtWidgets.QFrame(self.frame_5)
        self.frame2.setGeometry(QtCore.QRect(120, 20, 34, 148))
        self.frame2.setStyleSheet("QFrame {background:rgb(0, 0, 0);}")
        self.frame2.setObjectName("frame2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame2)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.img_R1 = QtWidgets.QLabel(self.frame2)
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.img_R1.setFont(font)
        self.img_R1.setText("")
        self.img_R1.setAlignment(QtCore.Qt.AlignCenter)
        self.img_R1.setObjectName("img_R1")
        self.verticalLayout_7.addWidget(self.img_R1)
        self.img_R2 = QtWidgets.QLabel(self.frame2)
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.img_R2.setFont(font)
        self.img_R2.setText("")
        self.img_R2.setAlignment(QtCore.Qt.AlignCenter)
        self.img_R2.setObjectName("img_R2")
        self.verticalLayout_7.addWidget(self.img_R2)
        self.img_R3 = QtWidgets.QLabel(self.frame2)
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.img_R3.setFont(font)
        self.img_R3.setText("")
        self.img_R3.setAlignment(QtCore.Qt.AlignCenter)
        self.img_R3.setObjectName("img_R3")
        self.verticalLayout_7.addWidget(self.img_R3)
        self.img_R4 = QtWidgets.QLabel(self.frame2)
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.img_R4.setFont(font)
        self.img_R4.setText("")
        self.img_R4.setAlignment(QtCore.Qt.AlignCenter)
        self.img_R4.setObjectName("img_R4")
        self.verticalLayout_7.addWidget(self.img_R4)
        self.frame_6 = QtWidgets.QFrame(self.frame_3)
        self.frame_6.setGeometry(QtCore.QRect(470, 10, 161, 181))
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.frame_6.setFont(font)
        self.frame_6.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setMidLineWidth(0)
        self.frame_6.setObjectName("frame_6")
        self.img_B2 = QtWidgets.QLabel(self.frame_6)
        self.img_B2.setGeometry(QtCore.QRect(10, 60, 72, 23))
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.img_B2.setFont(font)
        self.img_B2.setText("")
        self.img_B2.setPixmap(QtGui.QPixmap("../../../.designer/backup/uncheck.png"))
        self.img_B2.setAlignment(QtCore.Qt.AlignCenter)
        self.img_B2.setObjectName("img_B2")
        self.img_B1 = QtWidgets.QLabel(self.frame_6)
        self.img_B1.setGeometry(QtCore.QRect(10, 100, 72, 23))
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.img_B1.setFont(font)
        self.img_B1.setText("")
        self.img_B1.setPixmap(QtGui.QPixmap("../../../.designer/backup/uncheck.png"))
        self.img_B1.setAlignment(QtCore.Qt.AlignCenter)
        self.img_B1.setObjectName("img_B1")
        self.laser_state_B = QtWidgets.QLabel(self.frame_3)
        self.laser_state_B.setGeometry(QtCore.QRect(640, 20, 281, 161))
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.laser_state_B.setFont(font)
        self.laser_state_B.setStyleSheet("font: bold 13pt \"나눔고딕\";")
        self.laser_state_B.setAlignment(QtCore.Qt.AlignCenter)
        self.laser_state_B.setObjectName("laser_state_B")
        self.btn_one = QtWidgets.QPushButton(self.centralwidget)
        self.btn_one.setEnabled(True)
        self.btn_one.setGeometry(QtCore.QRect(1100, 800, 211, 201))
        self.btn_one.setMinimumSize(QtCore.QSize(0, 0))
        self.btn_one.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btn_one.setFont(font)
        self.btn_one.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_one.setMouseTracking(False)
        self.btn_one.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btn_one.setStyleSheet("QPushButton{ \n"
"background:rgb(0, 191, 137);\n"
"color:#fff; \n"
"font-size:18pt;\n"
" border: 3px solid rgb(200, 200, 200);\n"
" position:relative;\n"
" height:60px;\n"
" cursor:pointer;\n"
" outline:none;\n"
"}\n"
"QPushButton:hover{\n"
"  background:rgb(220, 220, 220);\n"
"  color:rgb(0, 0, 0);\n"
"  border: 2px solid rgb(33, 33, 33);\n"
"}")
        self.btn_one.setObjectName("btn_one")
        self.frame_8 = QtWidgets.QFrame(self.centralwidget)
        self.frame_8.setGeometry(QtCore.QRect(1100, 30, 801, 741))
        self.frame_8.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_8.setObjectName("frame_8")
        self.layoutWidget1 = QtWidgets.QWidget(self.frame_8)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 10, 781, 721))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.splitter_4 = QtWidgets.QSplitter(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.splitter_4.setFont(font)
        self.splitter_4.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_4.setObjectName("splitter_4")
        self.label_8 = QtWidgets.QLabel(self.splitter_4)
        self.label_8.setMaximumSize(QtCore.QSize(16777215, 41))
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_4.addWidget(self.splitter_4)
        self.msg_0 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.msg_0.setFont(font)
        self.msg_0.setStyleSheet("QLabel{  \n"
"border-bottom: 1px solid rgb(150, 150, 150); \n"
"color: rgb(255, 0, 0);\n"
"font: bold 16pt;\n"
"}")
        self.msg_0.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.msg_0.setObjectName("msg_0")
        self.verticalLayout_4.addWidget(self.msg_0)
        self.msg_1 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.msg_1.setFont(font)
        self.msg_1.setStyleSheet("QLabel{  \n"
"border-bottom: 1px solid rgb(150, 150, 150); \n"
"color: rgb(0, 0, 0);\n"
"font: bold 14pt;\n"
"}")
        self.msg_1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.msg_1.setObjectName("msg_1")
        self.verticalLayout_4.addWidget(self.msg_1)
        self.msg_2 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.msg_2.setFont(font)
        self.msg_2.setStyleSheet("QLabel{  \n"
"border-bottom: 1px solid rgb(150, 150, 150); \n"
"color: rgb(33, 33, 33);\n"
"font: bold 14pt;\n"
"}")
        self.msg_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.msg_2.setObjectName("msg_2")
        self.verticalLayout_4.addWidget(self.msg_2)
        self.msg_3 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.msg_3.setFont(font)
        self.msg_3.setStyleSheet("QLabel{  \n"
"border-bottom: 1px solid rgb(150, 150, 150); \n"
"color: rgb(82, 82, 82);\n"
"font: bold 14pt;\n"
"}")
        self.msg_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.msg_3.setObjectName("msg_3")
        self.verticalLayout_4.addWidget(self.msg_3)
        self.msg_4 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.msg_4.setFont(font)
        self.msg_4.setStyleSheet("QLabel{  \n"
"border-bottom: 1px solid rgb(150, 150, 150); \n"
"color: rgb(116, 116, 116);\n"
"font: bold 14pt;\n"
"}")
        self.msg_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.msg_4.setObjectName("msg_4")
        self.verticalLayout_4.addWidget(self.msg_4)
        self.msg_5 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.msg_5.setFont(font)
        self.msg_5.setStyleSheet("QLabel{  \n"
"color: rgb(167, 167, 167);\n"
"font: bold 14pt;\n"
"}")
        self.msg_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.msg_5.setObjectName("msg_5")
        self.verticalLayout_4.addWidget(self.msg_5)
        self.setting = QtWidgets.QPushButton(self.centralwidget)
        self.setting.setGeometry(QtCore.QRect(1760, 800, 141, 91))
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.setting.setFont(font)
        self.setting.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.setting.setStyleSheet("QPushButton{\n"
"  border: 3px solid rgb(200, 200, 200);\n"
"  position:relative;\n"
"  height:60px;\n"
"  cursor:pointer;\n"
"  outline:none;\n"
"}\n"
"QPushButton:hover{\n"
"   background:rgb(220, 220, 220);\n"
"  color:rgb(0, 0, 0);\n"
"  border: 2px solid rgb(33, 33, 33);\n"
"}")
        self.setting.setObjectName("setting")
        self.btn_exit = QtWidgets.QPushButton(self.centralwidget)
        self.btn_exit.setGeometry(QtCore.QRect(1760, 900, 141, 101))
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btn_exit.setFont(font)
        self.btn_exit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_exit.setStyleSheet("QPushButton{ \n"
"background: rgb(0, 0, 0);\n"
"color:#fff; \n"
"  border: 3px solid rgb(200, 200, 200);\n"
"  position:relative;\n"
"  height:60px;\n"
"  cursor:pointer;\n"
"  outline:none;\n"
"}\n"
"QPushButton:hover{\n"
"  background:rgb(220, 220, 220);\n"
"  color:rgb(0, 0, 0);\n"
"  border: 2px solid rgb(33, 33, 33);\n"
"}")
        self.btn_exit.setObjectName("btn_exit")
        self.btn_all = QtWidgets.QPushButton(self.centralwidget)
        self.btn_all.setEnabled(True)
        self.btn_all.setGeometry(QtCore.QRect(1320, 800, 211, 201))
        self.btn_all.setMinimumSize(QtCore.QSize(0, 0))
        self.btn_all.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btn_all.setFont(font)
        self.btn_all.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_all.setMouseTracking(False)
        self.btn_all.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btn_all.setStyleSheet("QPushButton{ \n"
"background: rgb(0, 150, 110);\n"
"color:#fff; \n"
"font-size:18pt;\n"
" border: 3px solid rgb(200, 200, 200);\n"
" position:relative;\n"
" height:60px;\n"
" cursor:pointer;\n"
" outline:none;\n"
"}\n"
"QPushButton:hover{\n"
"  background:rgb(220, 220, 220);\n"
"  color:rgb(0, 0, 0);\n"
"  border: 2px solid rgb(33, 33, 33);\n"
"}")
        self.btn_all.setObjectName("btn_all")
        self.splitter_6 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_6.setGeometry(QtCore.QRect(170, 772, 181, 31))
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.splitter_6.setFont(font)
        self.splitter_6.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_6.setObjectName("splitter_6")
        self.img_info_3 = QtWidgets.QLabel(self.splitter_6)
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.img_info_3.setFont(font)
        self.img_info_3.setAlignment(QtCore.Qt.AlignCenter)
        self.img_info_3.setObjectName("img_info_3")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(20, 800, 131, 201))
        self.frame_2.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.frame_2.setFont(font)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_2.setObjectName("frame_2")
        self.layoutWidget2 = QtWidgets.QWidget(self.frame_2)
        self.layoutWidget2.setGeometry(QtCore.QRect(5, 11, 121, 181))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("QLabel{ font: bold 13pt;}")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_2.addWidget(self.label_6)
        self.img_Lsock = QtWidgets.QLabel(self.layoutWidget2)
        self.img_Lsock.setMinimumSize(QtCore.QSize(32, 0))
        self.img_Lsock.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.img_Lsock.setFont(font)
        self.img_Lsock.setStyleSheet("QLabel{ font: bold 11pt; }")
        self.img_Lsock.setText("")
        self.img_Lsock.setPixmap(QtGui.QPixmap("../../../.designer/backup/unchecked.png"))
        self.img_Lsock.setAlignment(QtCore.Qt.AlignCenter)
        self.img_Lsock.setObjectName("img_Lsock")
        self.verticalLayout_2.addWidget(self.img_Lsock)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("QLabel{ font: bold 13pt;}")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.img_Rsock = QtWidgets.QLabel(self.layoutWidget2)
        self.img_Rsock.setMinimumSize(QtCore.QSize(32, 0))
        self.img_Rsock.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.img_Rsock.setFont(font)
        self.img_Rsock.setStyleSheet("QLabel{ font: bold 11pt; }")
        self.img_Rsock.setText("")
        self.img_Rsock.setPixmap(QtGui.QPixmap("../../../.designer/backup/unchecked.png"))
        self.img_Rsock.setAlignment(QtCore.Qt.AlignCenter)
        self.img_Rsock.setObjectName("img_Rsock")
        self.verticalLayout_2.addWidget(self.img_Rsock)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("QLabel{ font: bold 13pt;}")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_2.addWidget(self.label_7)
        self.img_Bsock = QtWidgets.QLabel(self.layoutWidget2)
        self.img_Bsock.setMinimumSize(QtCore.QSize(32, 0))
        self.img_Bsock.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.img_Bsock.setFont(font)
        self.img_Bsock.setStyleSheet("QLabel{ font: bold 11pt;}")
        self.img_Bsock.setText("")
        self.img_Bsock.setPixmap(QtGui.QPixmap("../../../.designer/backup/unchecked.png"))
        self.img_Bsock.setAlignment(QtCore.Qt.AlignCenter)
        self.img_Bsock.setObjectName("img_Bsock")
        self.verticalLayout_2.addWidget(self.img_Bsock)
        self.splitter_3 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_3.setGeometry(QtCore.QRect(30, 773, 111, 31))
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.splitter_3.setFont(font)
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName("splitter_3")
        self.label_3 = QtWidgets.QLabel(self.splitter_3)
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.layoutWidget3 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget3.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.btn_all_ten = QtWidgets.QPushButton(self.centralwidget)
        self.btn_all_ten.setEnabled(True)
        self.btn_all_ten.setGeometry(QtCore.QRect(1540, 800, 211, 201))
        self.btn_all_ten.setMinimumSize(QtCore.QSize(0, 0))
        self.btn_all_ten.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btn_all_ten.setFont(font)
        self.btn_all_ten.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_all_ten.setMouseTracking(False)
        self.btn_all_ten.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btn_all_ten.setStyleSheet("QPushButton{ \n"
"background: rgb(0, 109, 80);\n"
"color:#fff; \n"
"font-size:18pt;\n"
" border: 3px solid rgb(200, 200, 200);\n"
" position:relative;\n"
" height:60px;\n"
" cursor:pointer;\n"
" outline:none;\n"
"}\n"
"QPushButton:hover{\n"
"  background:rgb(220, 220, 220);\n"
"  color:rgb(0, 0, 0);\n"
"  border: 2px solid rgb(33, 33, 33);\n"
"}")
        self.btn_all_ten.setObjectName("btn_all_ten")
        self.layoutWidget.raise_()
        self.btn_one.raise_()
        self.layer_R4.raise_()
        self.layer_R2.raise_()
        self.layer_L4.raise_()
        self.layer_L2.raise_()
        self.graphicsView.raise_()
        self.layer_L3.raise_()
        self.layer_L1.raise_()
        self.layer_R1.raise_()
        self.layer_R3.raise_()
        self.frame.raise_()
        self.frame_4.raise_()
        self.frame_3.raise_()
        self.frame_8.raise_()
        self.setting.raise_()
        self.btn_exit.raise_()
        self.btn_all.raise_()
        self.splitter_6.raise_()
        self.frame_2.raise_()
        self.splitter_3.raise_()
        self.btn_all_ten.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.actionAbout_System = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        self.actionAbout_System.setFont(font)
        self.actionAbout_System.setObjectName("actionAbout_System")
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setPointSize(14)
        self.action.setFont(font)
        self.action.setObjectName("action")

        self.retranslateUi(MainWindow)
        self.setting.clicked.connect(MainWindow.slot_menu)
        self.btn_exit.clicked.connect(MainWindow.slot_exit)
        self.btn_one.clicked.connect(MainWindow.slot_ok)
        self.btn_all.clicked.connect(MainWindow.slot_ok)
        self.btn_all_ten.clicked.connect(MainWindow.slot_ok)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_5.setText(_translate("MainWindow", "좌표계 결과"))
        self.information_LR.setText(_translate("MainWindow", "왼쪽 / 오른쪽"))
        self.information_UD.setText(_translate("MainWindow", "위 / 아래"))
        self.laser_state_RL.setText(_translate("MainWindow", "설명 1"))
        self.laser_state_B.setText(_translate("MainWindow", "설명 2"))
        self.btn_one.setText(_translate("MainWindow", "1회 측정"))
        self.label_8.setText(_translate("MainWindow", "측정 결과"))
        self.msg_0.setText(_translate("MainWindow", "Text 확인"))
        self.msg_1.setText(_translate("MainWindow", "Text 확인"))
        self.msg_2.setText(_translate("MainWindow", "Text 확인"))
        self.msg_3.setText(_translate("MainWindow", "Text 확인"))
        self.msg_4.setText(_translate("MainWindow", "Text 확인"))
        self.msg_5.setText(_translate("MainWindow", "Text 확인"))
        self.setting.setText(_translate("MainWindow", "셋팅"))
        self.btn_exit.setText(_translate("MainWindow", "종료"))
        self.btn_all.setText(_translate("MainWindow", "전면/후면\n"
"5회 연속 측정"))
        self.img_info_3.setText(_translate("MainWindow", "레이저 측정 상태"))
        self.label_6.setText(_translate("MainWindow", "좌측 레이저"))
        self.label_2.setText(_translate("MainWindow", "우측 레이저"))
        self.label_7.setText(_translate("MainWindow", "후면 레이저"))
        self.label_3.setText(_translate("MainWindow", "통신 상태"))
        self.btn_all_ten.setText(_translate("MainWindow", "전면/후면\n"
"10회 연속 측정"))
        self.actionAbout_System.setText(_translate("MainWindow", "about System"))
        self.action.setText(_translate("MainWindow", "시스템 셋팅"))
        self.action.setIconText(_translate("MainWindow", "setting"))
        self.action.setToolTip(_translate("MainWindow", "setting"))

