# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1840, 1479)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.splitter_2 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_2.setGeometry(QtCore.QRect(130, 20, 1661, 131))
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.splitter = QtWidgets.QSplitter(self.splitter_2)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.system_information = QtWidgets.QLabel(self.splitter)
        self.system_information.setMinimumSize(QtCore.QSize(500, 0))
        self.system_information.setMaximumSize(QtCore.QSize(500, 16777215))
        self.system_information.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.system_information.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.system_information.setObjectName("system_information")
        self.information = QtWidgets.QLabel(self.splitter)
        self.information.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.information.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.information.setObjectName("information")
        self.frame_3 = QtWidgets.QFrame(self.splitter_2)
        self.frame_3.setMaximumSize(QtCore.QSize(200, 16777215))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label = QtWidgets.QLabel(self.frame_3)
        self.label.setGeometry(QtCore.QRect(50, 10, 72, 23))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.layoutWidget = QtWidgets.QWidget(self.frame_3)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 40, 171, 91))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.radioButton = QtWidgets.QRadioButton(self.layoutWidget)
        self.radioButton.setObjectName("radioButton")
        self.verticalLayout.addWidget(self.radioButton)
        self.radioButton_2 = QtWidgets.QRadioButton(self.layoutWidget)
        self.radioButton_2.setObjectName("radioButton_2")
        self.verticalLayout.addWidget(self.radioButton_2)
        self.pushButton = QtWidgets.QPushButton(self.splitter_2)
        self.pushButton.setMaximumSize(QtCore.QSize(200, 16777215))
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setObjectName("pushButton")
        self.layer_e = QtWidgets.QLCDNumber(self.centralwidget)
        self.layer_e.setEnabled(True)
        self.layer_e.setGeometry(QtCore.QRect(1200, 450, 100, 30))
        self.layer_e.setFrameShape(QtWidgets.QFrame.HLine)
        self.layer_e.setFrameShadow(QtWidgets.QFrame.Plain)
        self.layer_e.setLineWidth(5)
        self.layer_e.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.layer_e.setObjectName("layer_e")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(149, 209, 1041, 1581))
        self.graphicsView.setObjectName("graphicsView")
        self.layer_a = QtWidgets.QLCDNumber(self.centralwidget)
        self.layer_a.setGeometry(QtCore.QRect(36, 443, 100, 30))
        self.layer_a.setFrameShape(QtWidgets.QFrame.HLine)
        self.layer_a.setFrameShadow(QtWidgets.QFrame.Plain)
        self.layer_a.setLineWidth(5)
        self.layer_a.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.layer_a.setObjectName("layer_a")
        self.layer_g = QtWidgets.QLCDNumber(self.centralwidget)
        self.layer_g.setEnabled(True)
        self.layer_g.setGeometry(QtCore.QRect(1200, 690, 100, 30))
        self.layer_g.setFrameShape(QtWidgets.QFrame.HLine)
        self.layer_g.setFrameShadow(QtWidgets.QFrame.Plain)
        self.layer_g.setLineWidth(5)
        self.layer_g.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.layer_g.setObjectName("layer_g")
        self.layer_b = QtWidgets.QLCDNumber(self.centralwidget)
        self.layer_b.setGeometry(QtCore.QRect(36, 563, 100, 30))
        self.layer_b.setFrameShape(QtWidgets.QFrame.HLine)
        self.layer_b.setFrameShadow(QtWidgets.QFrame.Plain)
        self.layer_b.setLineWidth(5)
        self.layer_b.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.layer_b.setObjectName("layer_b")
        self.layer_d = QtWidgets.QLCDNumber(self.centralwidget)
        self.layer_d.setGeometry(QtCore.QRect(36, 813, 100, 30))
        self.layer_d.setFrameShape(QtWidgets.QFrame.HLine)
        self.layer_d.setFrameShadow(QtWidgets.QFrame.Plain)
        self.layer_d.setLineWidth(5)
        self.layer_d.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.layer_d.setObjectName("layer_d")
        self.layer_f = QtWidgets.QLCDNumber(self.centralwidget)
        self.layer_f.setEnabled(True)
        self.layer_f.setGeometry(QtCore.QRect(1200, 570, 100, 30))
        self.layer_f.setFrameShape(QtWidgets.QFrame.HLine)
        self.layer_f.setFrameShadow(QtWidgets.QFrame.Plain)
        self.layer_f.setLineWidth(5)
        self.layer_f.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.layer_f.setObjectName("layer_f")
        self.layer_h = QtWidgets.QLCDNumber(self.centralwidget)
        self.layer_h.setEnabled(True)
        self.layer_h.setGeometry(QtCore.QRect(1200, 820, 100, 30))
        self.layer_h.setFrameShape(QtWidgets.QFrame.HLine)
        self.layer_h.setFrameShadow(QtWidgets.QFrame.Plain)
        self.layer_h.setLineWidth(5)
        self.layer_h.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.layer_h.setObjectName("layer_h")
        self.layer_c = QtWidgets.QLCDNumber(self.centralwidget)
        self.layer_c.setGeometry(QtCore.QRect(36, 683, 100, 30))
        self.layer_c.setFrameShape(QtWidgets.QFrame.HLine)
        self.layer_c.setFrameShadow(QtWidgets.QFrame.Plain)
        self.layer_c.setLineWidth(5)
        self.layer_c.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.layer_c.setObjectName("layer_c")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1840, 31))
        self.menubar.setObjectName("menubar")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAbout_System = QtWidgets.QAction(MainWindow)
        self.actionAbout_System.setObjectName("actionAbout_System")
        self.menuHelp.addAction(self.actionAbout_System)
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.pushButton.clicked.connect(MainWindow.slot_ok)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.system_information.setText(_translate("MainWindow", "System Information Text"))
        self.information.setText(_translate("MainWindow", "Move Information Text"))
        self.label.setText(_translate("MainWindow", "Options"))
        self.radioButton.setText(_translate("MainWindow", "RadioButton1"))
        self.radioButton_2.setText(_translate("MainWindow", "RadioButton2"))
        self.pushButton.setText(_translate("MainWindow", "Measurement"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionAbout_System.setText(_translate("MainWindow", "about System"))

