# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(603, 699)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.splitter_2 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_2.setGeometry(QtCore.QRect(40, 40, 521, 121))
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.splitter = QtWidgets.QSplitter(self.splitter_2)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.qt_label_info_connection = QtWidgets.QLabel(self.splitter)
        self.qt_label_info_connection.setMinimumSize(QtCore.QSize(0, 0))
        self.qt_label_info_connection.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.qt_label_info_connection.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.qt_label_info_connection.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.qt_label_info_connection.setObjectName("qt_label_info_connection")
        self.widget = QtWidgets.QWidget(self.splitter)
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setSpacing(4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setLineWidth(1)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.qt_radio_onetime = QtWidgets.QRadioButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qt_radio_onetime.sizePolicy().hasHeightForWidth())
        self.qt_radio_onetime.setSizePolicy(sizePolicy)
        self.qt_radio_onetime.setChecked(True)
        self.qt_radio_onetime.setObjectName("qt_radio_onetime")
        self.verticalLayout.addWidget(self.qt_radio_onetime)
        self.qt_radio_roof = QtWidgets.QRadioButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qt_radio_roof.sizePolicy().hasHeightForWidth())
        self.qt_radio_roof.setSizePolicy(sizePolicy)
        self.qt_radio_roof.setObjectName("qt_radio_roof")
        self.verticalLayout.addWidget(self.qt_radio_roof)
        self.qt_measurement_btn = QtWidgets.QPushButton(self.splitter_2)
        self.qt_measurement_btn.setMaximumSize(QtCore.QSize(200, 16777215))
        self.qt_measurement_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.qt_measurement_btn.setObjectName("qt_measurement_btn")
        self.qt_scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.qt_scrollArea.setGeometry(QtCore.QRect(40, 190, 521, 431))
        self.qt_scrollArea.setWidgetResizable(True)
        self.qt_scrollArea.setObjectName("qt_scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 519, 429))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.qt_scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.splitter_2.raise_()
        self.qt_scrollArea.raise_()
        self.label.raise_()
        self.qt_radio_onetime.raise_()
        self.qt_radio_roof.raise_()
        self.label.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 603, 25))
        self.menubar.setObjectName("menubar")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAbout_System = QtWidgets.QAction(MainWindow)
        self.actionAbout_System.setObjectName("actionAbout_System")
        self.menuHelp.addAction(self.actionAbout_System)
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.qt_measurement_btn.clicked.connect(MainWindow.slot_ok)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Laser Module Checking Program by LN"))
        self.qt_label_info_connection.setText(_translate("MainWindow", "System Information Text"))
        self.label.setText(_translate("MainWindow", "Checking Option"))
        self.qt_radio_onetime.setText(_translate("MainWindow", "One time"))
        self.qt_radio_roof.setText(_translate("MainWindow", "Roof"))
        self.qt_measurement_btn.setText(_translate("MainWindow", "Measurement"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionAbout_System.setText(_translate("MainWindow", "about System"))

